baseURL: 'https://agusfahmiajipramana.com/'
title: Agus Fahmi Aji Pramana's Blogging Site
pagination:
  pagerSize: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
disqusShortname: agusfahmiajipramana-com


minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: 'English'
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # To enable google analytics, opengraph, twitter-cards and schema.
  description: 'Explore insightful blog posts and discover content based on a wide range of emerging technologies, programming, networking, and cybersecurity.'
  # prettier-ignore
  keywords: [Portfolio, Site, Blog, Blogging, Technology, Machine Learning, Networking, Programming, Software, Engineering, DevOps, DevSecOps, Sagar, Chamling, Sagar Chamling, Presentation, Training, Software Development, Cloud Computing, Cloud Security, Ethical Hacking, Penetration Testing]
  author: 'Agus Fahmi Aji Pramana'
  defaultTheme: auto
  disableThemeToggle: false
  showDate: true
  showDateUpdated: true
  showHeadingAnchors: true
  showPagination: true
  showReadingTime: true
  showTableOfContents: true
  showTaxonomies: false
  showWordCount: true
  showSummary: true
  sharingLinks: true
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  images: ['logo.svg']  
  comments: true

  profileMode:
    enabled: false
    title: 👋, I'm Agus Fahmi Aji Pramana,
    imageUrl: 'img/profile.webp'
    imageTitle: Agus Fahmi Aji Pramana's Photo
    imageWidth: 250
    imageHeight: 250
    imageFit: fill
    subtitle: 'A passionate full-stack software engineer and cyber security enthusiast. Explore my recent blog articles, where I write about my works, share valuable insights on emerging technologies, programming, networking and cybersecurity in a company accepted best practices and standards. Stay tuned for more!.'
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
      - name: '#tech'
        url: blogs/tech

  homeInfoParams:
    enabled: true
    imageUrl: 'img/profile.webp'
    imageTitle: Agus Fahmi Aji Pramana's Photo
    imageWidth: 250
    imageHeight: 250
    imageFit: fill
    buttons:
      - name: Tags
        url: tags
      - name: Notes
        url: notes
      - name: Categories
        url: categories
      - name: Archives
        url: archives

  socialIcons:
    - name: github
      url: 'https://github.com/agfmi'
    - name: x
      url: 'https://twitter.com/agfmi'
    - name: linkedin
      url: 'https://linkedin.com/in/agusfahmiajipramana'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/agus-fahmi-aji-pramana'
    - name: youtube
      url: 'https://www.youtube.com/@agusfahmiajipramana'
    - name: buymeacoffee
      url: 'https://www.buymeacoffee.com/agfmi'

  editPost:
    URL: 'https://github.com/agusfahmi/agusfahmiajipramana.com/tree/main/content'
    Text: 'Suggest Changes'
    appendFilePath: true

  label:
    text: "Agus Fahmi Aji Pramana"
    # icon: "img/apple-touch-icon.png"
    # iconHeight: 25

  assets:
    favicon: 'favicon.ico'
    favicon16x16: 'favicon-16x16.png'
    favicon32x32: 'favicon-32x32.png'
    apple_touch_icon: 'img/apple-touch-icon.png'
    safari_pinned_tab: 'safari-pinned-tab.svg'
    android_chrome192x192: 'img/android-chrome-192x192.png'
    android_chrome512x512: 'img/android-chrome-512x512.png'

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  x:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
  disqus:
    shortname: agusfahmiajipramana-com
  googleAnalytics:
    id: G-PJ6VCR89GD
    
