baseURL = 'https://agusfahmiajipramana.com/'
languageCode = 'en-us'
title = 'Agus Fahmi Aji Pramana'

[params]
	social = true
	
[services]
  [services.disqus]
    shortname = 'agusfahmiajipramana-com'